### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0

### ISSUE THREAD

**Issue by blessyezi** [alibaba/weex#1040]
扩展百度地图搜索module的时候jscallback返回前台时程序飞掉，错误日志如下：

```
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]     string: '{"result":"[{\"address\":\"秦淮区永乐路31号\",\"distance\":3935.0544479648124,\"name\":\"乐乐休闲网络\"},{\"address\":\"奥体大街169号环宇融侨广场2楼(手扶电梯上2楼右手即是)\",\"distance\":4917.053329133048,\"name\":\"青春飞扬网咖\"},{\"address\":\"秦淮区马道街12号(近秦淮国税局)\",\"distance\":4173.691275325252,\"name\":\"中录时空洪英达网络会所\"},{\"address\":\"江宁区胜太西路168号(近河海大学)\",\"distance\":4522.0729308379905,\"name\":\"踏浪网咖(胜太西路店)\"},{\"address\":\"建邺区泰山路购好超市旁\",\"distance\":3863.3229367097547,\"name\":\"一网情深网吧\"},{\"address\":\"秦淮区江宁路24-1号(公交车站)\",\"distance\":4307.82353228293,\"name\":\"极度空间网络\"},{\"address\":\"长虹路439号\",\"distance\":2903.056849745199,\"name\":\"欣网e家网吧\"},{\"address\":\"秦淮区大石坝街93-1号2楼(公交车站)\",\"distance\":4749.391175387147,\"na
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]     from int com.taobao.weex.bridge.WXBridge.execJS(java.lang.String, java.lang.String, java.lang.String, com.taobao.weex.bridge.WXJSObject[])
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65] "WeexJSBridgeThread" prio=5 tid=17 Runnable
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12dafa50 self=0xab149550
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   | sysTid=29762 nice=0 cgrp=default sched=0/0 handle=0xab149928
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 412242472 297124528 961 ) utm=32 stm=9 core=3 HZ=100
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   | stack=0xe48ba000-0xe48bc000 stackSize=1036KB
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #00 pc 000047e0  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00002ff9  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #02 pc 00242fb1  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+68)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #03 pc 00227359  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+144)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #04 pc 000aff6b  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+582)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #05 pc 000b06b1  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+60)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #06 pc 000b2b3b  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckEbPKcz.constprop.129+882)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000bb5b9  /system/lib/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+36)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #08 pc 00021cbd  /data/app/com.alibaba.weex-1/lib/arm/libweexv8.so (???)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #09 pc 00039990  /data/app/com.alibaba.weex-1/lib/arm/libweexv8.so (???)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   native: #10 pc 00000424   (???)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at com.taobao.weex.bridge.WXBridge.execJS(Native method)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at com.taobao.weex.bridge.WXBridgeManager.invokeExecJS(WXBridgeManager.java:858)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at com.taobao.weex.bridge.WXBridgeManager.invokeCallJSBatch(WXBridgeManager.java:951)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at com.taobao.weex.bridge.WXBridgeManager.handleMessage(WXBridgeManager.java:825)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:98)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
08-22 13:47:24.274 29697-29762/com.alibaba.weex A/art: art/runtime/check_jni.cc:65]   at android.os.HandlerThread.run(HandlerThread.java:61)
```

又改了一下代码，好像不报了。代码大概是这样的

```
public class BaiduSearchModule extends WXModule implements BDLocationListener,OnGetPoiSearchResultListener {

    JSCallback jsCallback;

    boolean firstOp = true;

    @WXModuleAnno
    public void searchByText(BaiduSearchOption searchOption, JSCallback jsCallback) {
        ...
        this.jsCallback = jsCallback;
        if (firstOp == true) {
            ...
        }
        ...
    }


    @Override
    public void onGetPoiResult(PoiResult poiResult) {
        ...
        jsCallback.invoke(resultMap);

    }
}
```

改成这样

```
public class BaiduSearchModule extends WXModule implements BDLocationListener,OnGetPoiSearchResultListener {

    JSCallback jsCallback;

    boolean firstOp = true;

    @WXModuleAnno
    public void searchByText(BaiduSearchOption searchOption, JSCallback jsCallback) {
        ...
        if (firstOp == true) {
            ...
            this.jsCallback = jsCallback;
        }
        ...
    }


    @Override
    public void onGetPoiResult(PoiResult poiResult) {
        ...
        jsCallback.invoke(resultMap);

    }
}

```

成员变量中有一个jsCallback，为了在回调方法中能够使用jsCallback。如果每次调用searchByText方法时，都给这个成员变量赋值，this.jsCallback = jsCallback，在多调用几次之后，就会出现我贴的出错。如果只在第一次调用module方法时候赋值，貌似就不再报错了，这是啥原因啊？

**Comment by zshshr** [comment]
@blessyezi 你用的weex sdk 什么版本？

**Comment by zshshr** [comment]
0.8.0+ 新版本应该解决了这个问题
