### ISSUE TITLE
main.js是weex SDK的保留初始化js boundle文件，不可以将自己的APP中的js文件命名为main.js

### ISSUE THREAD

**Issue by Lurkyli** [alibaba/weex#1072]
我在创建自己的weex APP工程时，将js boundle文件命名为main.js，结果每次启动报错如下：
08-26 10:22:12.940 10908-10996/cn.com E/jsengine:  ReportException :(weex):47: ReferenceError: __weex_define__ is not defined
08-26 10:22:12.944 10908-10996/cn.com E/jsengine:  ReportException : ReferenceError: __weex_define__ is not defined
                                                                   at Object.<anonymous> ((weex):47:3)
                                                                   at __webpack_require__ ((weex):20:30)
                                                                   at (weex):40:18
                                                                   at (weex):43:10
08-26 10:22:13.012 10908-10908/cn.com I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
                                                             
                                                             [ 08-26 10:22:13.179  2930: 2930 E/         ]
                                                             process stopped due to unexpected signal 13
08-26 10:22:13.228 10908-11007/cn.com E/HAL: load: id=gralloc != hmi->id=gralloc
08-26 10:22:13.229 10908-11007/cn.com I/OpenGLRenderer: Initialized EGL, version 1.4
08-26 10:22:14.985 10908-10908/cn.com E/WXTBUtil: isSupportSmartBar:false
08-26 10:22:19.965 10908-10996/cn.com E/weex: reportJSException >>>> instanceId:null, exception function:, exception:ReferenceError: __weex_define__ is not defined
08-26 10:22:19.971 10908-10996/cn.com E/weex: [WXBridgeManager] invokeInitFramework java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                               at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772)
                                                               at com.taobao.weex.ui.WXRenderManager.getWXSDKInstance(WXRenderManager.java:251)
                                                               at com.taobao.weex.WXSDKManager.getSDKInstance(WXSDKManager.java:217)
                                                               at com.taobao.weex.bridge.WXBridgeManager.reportJSException(WXBridgeManager.java:1093)
                                                               at com.taobao.weex.bridge.WXBridge.reportJSException(WXBridge.java:267)
                                                               at com.taobao.weex.bridge.WXBridge.initFramework(Native Method)
                                                               at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:904)
                                                               at com.taobao.weex.bridge.WXBridgeManager.invokeInitFramework(WXBridgeManager.java:886)
                                                               at com.taobao.weex.bridge.WXBridgeManager.handleMessage(WXBridgeManager.java:822)
                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                               at android.os.Looper.loop(Looper.java:150)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
08-26 10:22:19.981 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
08-26 10:22:19.982 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
08-26 10:22:19.983 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
08-26 10:22:19.983 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
08-26 10:22:19.984 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
08-26 10:22:19.984 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
08-26 10:22:19.985 10908-10996/cn.com E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.

原因是：
weex sdk的WXBridgeManager::WXBridgeManager中的出事化代码用到了main.js：
      if (TextUtils.isEmpty(framework)) {
        if (WXEnvironment.isApkDebugable()) {
          WXLogUtils.d("weex JS framework from assets");
        }
        framework = WXFileUtils.loadAsset("main.js", WXEnvironment.getApplication());
      }
APP中新创建的main.js与SDK中的main.js冲突，导致SDK中的main.js被APP中的main.js覆盖，致使WXBridgeManager无法初始化。

解决方案：
APP中开发的js文件，名称不能与weex SDK中使用的js boundle文件重名。

建议：
weex公布sdk中保留的js boundle文件名称，避免因js文件重名导致程序BUG。

**Comment by luics** [comment]
目前只有 main.js ，后续我们整理到文档中，谢谢反馈。

**Comment by qbcbyb** [comment]
比较坑的是之前本人通过weex init出来的工程默认的we文件就是main.we，生成的就是main.js。

**Comment by Jinjiang** [comment]
@lvscar 我们可以考虑新的 weex init 之后默认文件换个别的名字，尽量回避和 `main.js` 之间的矛盾

**Comment by lvscar** [comment]
weex-bootstrap.js   ？

**Comment by lvscar** [comment]
Latest version of weex-toolkit(0.5.10)  have renamed weex entry file and  have updated webpack configuration which are generated by weex init.  No more main.we and main.js now.

Please install weex-toolkit and use  'weex init' to create project template.
