### ISSUE TITLE
Unknown plugin "babel-plugin-transform-runtime" specified

### ISSUE THREAD

**Issue by namedlock** [alibaba/weex#1281]
### 基本信息：
* mac OSX EI Capitan 10.11.6
* node 4.5.0
* weex-toolkit 0.4.0
* npm 2.15.9
* weex dev分支 https://github.com/alibaba/weex/commit/ec10e8d3e9946c88f11aa9237a0879d3c8d5aae3

### 复现步骤：
* 在dev分支下载2016-09-22 dev分支代码
* 执行npm install
* 执行./start

```
ERROR in ./~/weex-loader/lib/script.js!./~/babel-loader?presets[]=/Users/keen/workspace/weex-all/weex-master/~/weex-loader/~/babel-preset-es2015&presets=/Users/keen/workspace/weex-all/weex-master/~/weex-loader/~/babel-preset-es2015&plugins[]=/Users/keen/workspace/weex-all/weex-master/~/weex-loader/~/babel-plugin-transform-runtime&plugins=/Users/keen/workspace/weex-all/weex-master/~/weex-loader/~/babel-plugin-transform-runtime&comments=false!./~/weex-loader/lib/extract.js?index=0&type=scripts!./examples/index.we
Module build failed: ReferenceError: Unknown plugin "/Users/keen/workspace/weex-all/weex-master/node_modules/weex-loader/node_modules/babel-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/keen/workspace/weex-all/weex-master/examples"
    at /Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/keen/workspace/weex-all/weex-master/node_modules/babel-loader/index.js:131:12)
 @ ./examples/index.we?entry=true 2:22-645
```

### 临时解决方案
* 修改package.json "weex-loader": "^0.1.5"

**Comment by dodola** [comment]
同出现这个问题，用npm-check 检查了一下
```

kountdown            😟  MISSING!  Not installed.
                     😟  PKG ERR!  Not in the package.json. Found in: /html5/browser/extend/components/countdown.js

@weex-component/a    😟  MISSING!  Not installed.
                     😟  PKG ERR!  Not in the package.json. Found in: /html5/test/unit/default/app/bundle.js
                     ⛔️  NPM ERR!  Registry error Package `@weex-component/a` doesn't exist

@weex-module/dom     😟  MISSING!  Not installed.
                     😟  PKG ERR!  Not in the package.json. Found in: /html5/test/unit/default/app/bundle.js
                     ⛔️  NPM ERR!  Registry error Package `@weex-module/dom` doesn't exist

lib-httpurl          😟  MISSING!  Not installed.
                     😟  PKG ERR!  Not in the package.json. Found in: /html5/test/unit/default/app/bundle.js
                     ⛔️  NPM ERR!  Registry error Package `lib-httpurl` doesn't exist

```

**Comment by dodola** [comment]
同出现这个问题，临时解决方案，回退package.json
```
    "weex-components": "^0.1.3"
    "weex-loader": "^0.2.0"

```

```bash
weex@0.4.0 /Volumes/Mac/github/weex
├── weex-components@0.1.4 
└── weex-loader@0.2.3 

```

**Comment by 280772270** [comment]
楼上+1

**Comment by SimonTal** [comment]
不用退到这么前的版本，目前我项目的依赖文件是：

**Comment by zuibunan** [comment]
我的更新weex-toolkit到最新版本就好了

**Comment by lvscar** [comment]
latest version ov weex-toolkit should fix the bug
