### ISSUE TITLE
fs.js:1315 throw error;

### ISSUE THREAD

**Issue by sunxiaoyang** [alibaba/weex#1393]
$weex ./test.we 

错误提示如下：
info Fri Oct 14 2016 17:09:31 GMT+0800 (CST)WebSocket  is listening on port 8082 
info Fri Oct 14 2016 17:09:31 GMT+0800 (CST)http  is listening on port 8081 
fs.js:1315
    throw error;
    ^

Error: watch . ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at watch (/usr/local/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:221:8)
    at /usr/local/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:180:14
    at Array.forEach (native)
    at /usr/local/lib/node_modules/weex-toolkit/node_modules/node-watch/lib/watch.js:179:13
    at Previewer.watchForWSRefresh (/usr/local/lib/node_modules/weex-toolkit/bin/weex.js:276:13)
    at WebSocketServer.connection (/usr/local/lib/node_modules/weex-toolkit/bin/weex.js:265:22)
    at emitOne (events.js:77:13)
    at WebSocketServer.emit (events.js:169:7)
    at /usr/local/lib/node_modules/weex-toolkit/node_modules/ws/lib/WebSocketServer.js:91:14
    at completeHybiUpgrade2 (/usr/local/lib/node_modules/weex-toolkit/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/usr/local/lib/node_modules/weex-toolkit/node_modules/ws/lib/WebSocketServer.js:306:13)
    at WebSocketServer.handleHybiUpgrade (/usr/local/lib/node_modules/weex-toolkit/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/usr/local/lib/node_modules/weex-toolkit/node_modules/ws/lib/WebSocketServer.js:173:26)

**Comment by Jinjiang** [comment]
请提供一下你的操作系统环境和Node版本
另外你的 `test.we` 是否在比较特殊的权限的文件夹下？尝试着换个目录试试看
谢谢

**Comment by Jinjiang** [comment]
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by alext1981** [comment]
作者超过9天未回复，暂时视为讨论中的意见已经帮助作者解决了问题，如果问题仍未解决，作者可reopen本issue并提供更多的信息，谢谢。

**Comment by passioncsu** [comment]
太牛了 果然是这个问题,链接完美的解决了我的问题,我就是arch用户

```
After doing some research found the solution. Run the below command.

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
For Arch Linux add this line to /etc/sysctl.d/99-sysctl.conf:

fs.inotify.max_user_watches=524288
```
