### ISSUE TITLE
BugsFix-Android 关于Weex在Android部份机型上面，页面不显示页面的问题

### ISSUE THREAD

**Issue by ManBali** [alibaba/weex#1411]
如果是 **_Bug**_，请提供：复现步骤（推荐有截图）、error/crash log、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。

重现的步骤如下所示：
http://note.youdao.com/noteshare?id=d5878ba7e13a2d427a595cbb8cdd8b6b

暂时没有找到原因

**Comment by wsf5918** [comment]
另外补充发现，在小米的机器上面显示没有问题

**Comment by wsf5918** [comment]
invokeCallJSBatch: framework.js uninitialized.

**Comment by wsf5918** [comment]
对了，我使用的是
https://bintray.com/alibabaweex/maven/weex_sdk/0.8.0.1  这个版本的gradle也不行

**Comment by wsf5918** [comment]
sh
10-17 19:02:38.731 29803-29803/com.chicv.stylewe I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e8fa583 time:61903016
10-17 19:02:38.731 29803-30900/com.chicv.stylewe E/art: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
10-17 19:02:38.731 29803-30900/com.chicv.stylewe E/weex: [WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
                                                             at com.taobao.weex.bridge.WXBridge.initFramework(Native Method)
                                                             at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1033)
                                                             at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:832)
                                                             at com.taobao.weex.bridge.WXBridgeManager.access$200(WXBridgeManager.java:273)
                                                             at com.taobao.weex.bridge.WXBridgeManager$5.run(WXBridgeManager.java:813)
                                                             at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:158)
                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
10-17 19:02:38.741 29803-30900/com.chicv.stylewe E/weex: [WXBridgeManager] invokeCreateInstance: framework.js uninitialized.

**Comment by zshshr** [comment]
invokeCallJSBatch: framework.js uninitialized. 这个错误日志表示初始化失败了，我本地尝试了三星S6的手机 用我们的最新的http://alibaba.github.io/weex/download.html，是正常的，初步估计你的初始化代码写的有问题，请用weex 的playground的demo安装试试，然后检查一下你的demo

**Comment by lanceliu** [comment]
我也遇到这个问题了，同求解决方案

**Comment by zshshr** [comment]
麻烦二位最好把完整的可复现的demo代码同步给我，我尝试本地复现一下。因为这个应该是个细节问题，你描述的方法，我没法重现。
如果你们方便本地调试的话可以单步一下初始化的流程，看看哪里调用失败里
这个日志显示是js framework没有初始化，但是有好几种情况会导致这个问题，第一，v8 so加载失败，导致无法初始化。第二你的手机可用内存比较小的时候，也会导致初始化失败。 @lanceliu  @wsf5918

**Comment by wsf5918** [comment]
@zshshr  我觉得，内存的问题，导致的初始化失败的原因，在我测试的机器上面，应该不太可能，手机使用的是galaxy  s6，应该来说，内存是足够的。  第二个是v8 so文件加载失败的？我没有看到过哪有v8 so文件尼？我是直接引用的仓库里面的资源:
compile 'com.taobao.android:weex_sdk:0.5.1'

**Comment by zshshr** [comment]
sdk是aar格式的，你解开你的app看看，lib下面有没有libweexv8.so这个文件 @wsf5918 ，还有你的版本比较老，用新版本，0.8.0版本试试

**Comment by lanceliu** [comment]
@zshshr 
好的，我本地的code怎么提供给你？

**Comment by lanceliu** [comment]
@zshshr 我用的 0.8.0.2版本，上面的问题解决了，但是报新的错。
如果是a 链接则会报错，
源码：
```javascript
	            {
	              "type": "a",
	              "attr": {
	                "href": function () {return this.pages['i-bio-desc']}
	              },
	              "children": [
	                {
	                  "type": "text",
	                  "attr": {
	                    "value": "个人简介"
	                  }
	                }
	              ]
	            },
```

报错信息
`10-25 13:57:42.462 2424-2453/org.yuntu.app E/weex: [WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
                                                       at com.taobao.weex.bridge.WXBridge.initFramework(Native Method)
                                                       at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1027)
                                                       at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:826)
                                                       at com.taobao.weex.bridge.WXBridgeManager.access$200(WXBridgeManager.java:273)
                                                       at com.taobao.weex.bridge.WXBridgeManager$5.run(WXBridgeManager.java:807)
                                                       at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by zshshr** [comment]
@lanceliu 你用最新的gihub上的android 分支试试，这个分支应该可以了

**Comment by fightKen** [comment]
我也遇到这个问题，具体报错如下：
No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
12-28 10:57:02.652 25290-25692/com.youcash.ZYWallet E/weex: [WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
                                                                at com.taobao.weex.bridge.WXBridge.initFramework(Native Method)
                                                                at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1037)
                                                                at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:839)
                                                                at com.taobao.weex.bridge.WXBridgeManager.access$200(WXBridgeManager.java:273)
                                                                at com.taobao.weex.bridge.WXBridgeManager$4.run(WXBridgeManager.java:820)
                                                                at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
12-28 10:57:02.652 25290-25692/com.youcash.ZYWallet E/weex: [WXBridgeManager] invokeCreateInstance: framework.js uninitialized.
机器是华为荣耀，可用内存2G，weex版本0.9.4。求解决方案

**Comment by wodis** [comment]
这个问题有解决方法了吗？用官方playground Demo没问题

**Comment by coderminer** [comment]
@wodis @fightKen @wsf5918

**Comment by coderminer** [comment]
@zshshr

**Comment by coderminer** [comment]
而且在arm64-v8a中没有libweexv8.so, 有的手机系统使用的应该是arm64架构，而在arm64-v8a中没有对应的so文件，导致加载失败

使用最新版本的sdk有同样的问题，解决方案  在app的build.grdle中添加 
    defaultConfig {
        ...
        ndk {
            abiFilters "x86"
            abiFilters "armeabi"
        }
    }

**Comment by fenglincanyi** [comment]
@zshshr , 我的项目 ndk 配置是：
``` gradle
ndk {
        abiFilters 'x86'
        abiFilters 'armeabi'
        abiFilters 'armeabi-v7a'
}
```
但是在生成的 apk 中，没有看到 armeabi-v7a 下的 weexv8.so 包，其他2个平台都有，这是什么情况？

**Comment by kevinTutu** [comment]
这个问题如何解决

**Comment by Pipikachu** [comment]
同求

**Comment by myeveryheart** [comment]
同求

**Comment by lovederh** [comment]
@fenglincanyi 怎么解决的后来

**Comment by personH** [comment]
有解决方案吗

**Comment by fenglincanyi** [comment]
> @fenglincanyi 怎么解决的后来

 全部使用 armeabi 平台

**Comment by fenglincanyi** [comment]
@lovederh 全部用 armeabi 平台的

**Comment by myeveryheart** [comment]
android 的 sdk 里面只包含了 armeabi 的 so，这就导致了如果你的 app 需要支持 armeabi-v7a 等，会因为找不到 so 库报初始化的相关错误。
解决的办法也很简单，解压出你的apk，找到 armeabi 里面所有 weex 相关的 so，拷贝到工程里面的 src/main/jniLibs/armeabi-v7a 文件夹里面，这样就支持了 armeabi-v7a 。如果你还要支持 arm64，那再建个 arm64-v8a  文件夹，一样拷 so 进去。参考 https://github.com/WeexBox/android-library/tree/master/core/src/main/jniLibs/armeabi-v7a
如果觉得麻烦，也可以直接使用 weexbox（http://weexbox.surge.sh/）。 文档还在整理中。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
