### ISSUE TITLE
[android]使用textarea 输入文字之后，滑动点击输入的地方，出现崩溃

### ISSUE THREAD

**Issue by jiangfei891111** [alibaba/weex#1454]
使用textarea 输入文字之后，滑动点击输入的地方，出现崩溃，此现象很频繁，几乎点着点着就崩溃了，

```
10-19 18:09:31.503 2170-2170/? I/Cliptray Service: cliptrayEventReceiver :onReceivecom.lge.systemservice.core.cliptray.INPUTTYPE_CLIPTRAY
10-19 18:09:31.925 1107-2263/? I/LGImmersionVibrator: Vibrator exists
10-19 18:09:31.931 2170-2170/? I/Cliptray Service: cliptrayEventReceiver :onReceivecom.lge.systemservice.core.cliptray.INPUTTYPE_CLIPTRAY
10-19 18:09:32.239 1694-1694/? E/[SystemUI]StatusBar.MSimNetworkController: updateDataNetType NETWORK_TYPE_UNKNOWN
10-19 18:09:32.457 18319-18319/cn.net.yiding I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
10-19 18:09:32.472 18319-18319/cn.net.yiding I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
10-19 18:09:33.047 1107-2185/? I/LGImmersionVibrator: Vibrator exists
10-19 18:09:33.073 18319-18319/cn.net.yiding E/SafeRunnable: SafeRunnable run throw expection:Attempt to invoke virtual method 'void android.widget.Editor$ActionPopupWindow.show()' on a null object reference
10-19 18:09:33.087 18319-18319/cn.net.yiding E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: cn.net.yiding, PID: 18319
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Editor$ActionPopupWindow.show()' on a null object reference
                                                                   at android.widget.Editor$HandleView$1.run(Editor.java:4040)
                                                                   at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
10-19 18:09:33.096 1107-2222/? W/ActivityManager:   Force finishing activity cn.net.yiding/.modules.weex.WeexEnterActivity
10-19 18:09:33.178 1107-1188/? I/PhoneWindow: [generateLayout] setColorNavigationBar => color=0x ff000001
10-19 18:09:33.181 1107-1188/? I/PhoneWindow: [setNavigationBarColor2] color=0x fff5f5f5
10-19 18:09:33.193 1107-1588/? I/InputDispatcher: Dropping event because there is no touchable window at (1060, 845).
10-19 18:09:33.195 1107-10078/? I/OpenGLRenderer: Initialized EGL, version 1.4
10-19 18:09:33.211 1107-1200/? I/SystemUI[Framework]: PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x8000, pkg=android
10-19 18:09:33.211 1694-1694/? I/[SystemUI]NavigationThemeResource: notify navigation bar color(0x0)
10-19 18:09:33.212 1107-1200/? W/PhoneWindowManagerEx: Call!!!getLGSystemUiVisibility. =0x0
10-19 18:09:33.212 1107-1200/? I/SystemUI[Framework]: ==>disabledNaviBtn() what=0x0, token=android.os.Binder@32c26d1,  pkg=WindowManager.LayoutParams
10-19 18:09:33.212 1107-1200/? I/SystemUI[Framework]: disableNaviBtn: mDisabledNaviBtn=0x0,  mDisableRecords.size=0
10-19 18:09:33.243 1694-1694/? E/[SystemUI]StatusBar.MSimNetworkController: updateDataNetType NETWORK_TYPE_UNKNOWN
10-19 18:09:33.677 1107-1188/? W/ActivityManager: Activity pause timeout for ActivityRecord{20f9c3aa u0 cn.net.yiding/.modules.weex.WeexEnterActivity t19364 f}
10-19 18:09:33.743 2264-2264/? I/[LGHome]EVENT: [Launcher.java:5351:onStart()]onStart
10-19 18:09:33.743 2264-2264/? I/[LGHome]EVENT: [Launcher.java:903:onResume()]onResume
10-19 18:09:33.753 1107-2204/? W/ActivityManager: Unable to start service Intent { act=com.lge.mrg.service.intent.action.APPEND_USER_LOG cmp=com.lge.mrg.service/.internal.ActionManagerService (has extras) } U=0: not found
10-19 18:09:33.753 2264-2264/? I/[LGHome]GBoardWebView: [GBoardWebView.java:306:loadCacheBitmapPostDelayed()]loadCacheBitmapPostDelayed() delay:1
10-19 18:09:33.755 2264-2264/? I/[LGHome]LGActivityUtil: [LGActivityUtil.java:319:notifyToWeatherWidget()]broadcast to weather widget, intent: Intent { act=com.lge.launcher2.RESUME }
10-19 18:09:33.757 2264-2264/? I/[LGHome]EVENT: [Launcher.java:1056:onResume()]onResume end
10-19 18:09:33.789 1107-2263/? W/ActivityManager: getTasks: caller 10069 does not hold GET_TASKS; limiting output
10-19 18:09:33.823 9381-9381/? I/WeatherReflect: Model Name : LG-D858
10-19 18:09:33.825 1107-2133/? W/ActivityManager: getTasks: caller 10069 does not hold GET_TASKS; limiting output
10-19 18:09:33.830 2264-2264/? I/[LGHome]GBoardWebView: [GBoardWebView.java:321:loadCacheBitmap()]loadCacheBitmap()
10-19 18:09:34.039 2264-2264/? I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@27d84512 time:261266458
10-19 18:09:34.266 1107-1202/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{9cf98f8 u0 com.lge.launcher2/.Launcher t18633} time:261266686
10-19 18:09:35.011 2264-3245/? I/GBoardtInterface: onAnimationFinished
10-19 18:09:35.067 13477-13477/? W/InputConnectionWrapper.ICC: Timed out waiting on IInputContextCallback
10-19 18:09:35.124 349-364/? E/GBMv2: DFP En is all cleared set to be enabled
10-19 18:09:35.124 349-364/? E/GBMv2: Set value is all cleared set the max
10-19 18:09:35.124 349-364/? I/GBMv2: DFP Enabled. Ignore VFP set
10-19 18:09:35.754 2264-3027/? I/[LGHome]NumberBadge.LGUnreadLgeEmailsBadge: [LGUnreadLgeEmailsBadge.java:107:countUnreadItems()]setTotalCount : 0
10-19 18:09:35.755 2264-3027/? I/[LGHome]NumberBadge.LGUnreadLgeEmailsBadge: [LGUnreadLgeEmailsBadge.java:108:countUnreadItems()]countUnreadItems() ended..
10-19 18:09:35.772 2264-3027/? I/[LGHome]NumberBadge.LGBroadCastBadge: [LGBroadCastBadge.java:53:updateBadgeIcon()][updateClassList : com.android.contacts.activities.DialtactsActivity = 0
10-19 18:09:35.773 2264-3027/? I/[LGHome]NumberBadge.LGBroadCastBadge: [LGBroadCastBadge.java:53:updateBadgeIcon()][updateClassList : com.kingroot.kinguser.activitys.SliderMainActivity = 1
10-19 18:09:35.774 2264-3027/? I/[LGHome]NumberBadge.LGBroadCastBadge: [LGBroadCastBadge.java:53:updateBadgeIcon()][updateClassList : com.android.mms.ui.ConversationList = 0
10-19 18:09:35.775 2264-3027/? I/[LGHome]NumberBadge.LGBroadCastBadge: [LGBroadCastBadge.java:53:updateBadgeIcon()][updateClassList : com.lge.updatecenter.UpdateCenterPrfActivity = 1
10-19 18:09:35.805 2264-2678/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-19 18:09:35.814 2264-2678/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-19 18:09:35.814 2264-2678/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-19 18:09:37.067 13477-13477/? W/InputConnectionWrapper.ICC: Timed out waiting on IInputContextCallback
10-19 18:09:37.068 13477-13477/? E/b: Unable to connect to the editor to retrieve text... will retry later
10-19 18:09:39.305 1107-2104/? I/art: Explicit concurrent mark sweep GC freed 68699(3MB) AllocSpace objects, 11(2MB) LOS objects, 32% free, 65MB/97MB, paused 4.123ms total 198.575ms
10-19 18:09:41.269 1694-1694/? E/[SystemUI]StatusBar.MSimNetworkController: updateDataNetType NETWORK_TYPE_UNKNOWN
10-19 18:09:42.304 1694-1694/? E/[SystemUI]StatusBar.MSimNetworkController: updateDataNetType NETWORK_TYPE_UNKNOWN
10-19 18:09:43.113 22217-22217/? I/sh: type=1400 audit(0.0:4122): avc: denied { execute_no_trans } for path="/system/xbin/su" dev="mmcblk0p40" ino=5094 scontext=u:r:rctd:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=1
10-19 18:09:43.123 22217-22217/? I/su: type=1400 audit(0.0:4123): avc: denied { getattr } for path="/data/data/com.kingroot.kinguser" dev="mmcblk0p42" ino=408251 scontext=u:r:rctd:s0 tcontext=u:object_r:app_data_file:s0 tclass=dir permissive=1
10-19 18:09:44.273 1107-1188/? W/ActivityManager: Activity destroy timeout for ActivityRecord{20f9c3aa u0 cn.net.yiding/.modules.weex.WeexEnterActivity t19364 f}
10-19 18:09:49.050 1694-1694/? I/[SystemUI]LGPowerUI: onReceive = com.lge.android.intent.action.BATTERYEX
10-19 18:09:49.052 1694-1694/? I/[SystemUI]LGPowerUI: levelEx = 100, plugTypeEx = 2, WirelessAlignment = 0, chargingCurrent = 0, orientation = PORTRAIT
10-19 18:09:49.052 1694-1694/? I/[SystemUI]LGPowerUI: On Skip Timer : true
10-19 18:09:49.063 1694-1694/? I/[SystemUI]LGPowerUI: onReceive = android.intent.action.BATTERY_CHANGED
10-19 18:09:49.063 1694-1694/? I/[SystemUI]LGPowerUI: level = 100, plugType = 2, plugged = true, mCharging = false, temperature = 380
10-19 18:09:49.067 2225-2225/? I/QCNEJ: |CORE| CNE received action: android.intent.action.BATTERY_CHANGED
10-19 18:09:49.067 2225-2225/? I/QCNEJ: |CORE| UpdateBatteryStatus status=5 pluginType=2 level=100
10-19 18:09:49.073 1694-1694/? I/[SystemUI]BatterySaverHandler: onReceive = android.intent.action.BATTERY_CHANGED
10-19 18:09:49.087 1107-1107/? W/Settings: Setting stay_on_while_plugged_in has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-19 18:09:49.087 1107-1107/? W/Settings: Setting wifi_sleep_policy has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-19 18:10:00.038 1694-1694/? I/[SystemUI]TimeTickManager: setTimeTickHandler, called onTimeChanged()
10-19 18:10:00.038 1694-1694/? I/KeyguardUpdateMonitor: called onTimeUpdated()
10-19 18:10:00.038 1694-1694/? I/[SystemUI]KeyguardIndicationController: called onTimeUpdated()
10-19 18:10:00.042 1694-1694/? I/[SystemUI]Clock: called onTimeUpdated()
10-19 18:10:00.047 1694-1694/? I/LgeClockWidgetControlView: called onTimeUpdated()
10-19 18:10:00.047 1694-1694/? I/[SystemUI]DateView: called onTimeUpdated()
10-19 18:10:00.048 1694-1694/? I/[SystemUI]DateView: called onTimeUpdated()
10-19 18:10:00.056 1107-2244/? W/ActivityManager: getTasks: caller 10069 does not hold GET_TASKS; limiting output
10-19 18:10:00.096 9381-9381/? I/WeatherReflect: Model Name : LG-D858
```

使用的Android weex SDK版本是：com.taobao.android:weex_sdk:0.8.0.1

测试手机: LG-D858   Android 5.0

**Comment by sospartan** [comment]
@jiangfei891111 你那里能稳定的复现这个问题么  我试了几台机器都没出现

**Comment by sospartan** [comment]
暂时定为系统框架的bug,Weex SDK还没办法解决,先关闭,如果其他手机上能够重现,请reopen.
