### ISSUE TITLE
[WXBridgeManager] invokeCreateInstance: framework.js uninitialized.

### ISSUE THREAD

**Issue by q757571446** [alibaba/weex#1527]
> 此异常发生于添加了一个带有so文件得library，例如

```
	compile 'com.github.barteksc:android-pdf-viewer:2.1.0'
```
> 异常信息
```
[WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
                                             at com.taobao.weex.bridge.WXBridge.initFramework(Native Method)
                                             at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1012)
                                             at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:811)
                                             at com.taobao.weex.bridge.WXBridgeManager.access$200(WXBridgeManager.java:273)
                                             at com.taobao.weex.bridge.WXBridgeManager$5.run(WXBridgeManager.java:792)
                                             at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                             at android.os.Handler.handleCallback(Handler.java:739)
                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                             at android.os.Looper.loop(Looper.java:135)
                                             at android.os.HandlerThread.run(HandlerThread.java:61)
```
> 解压apk后文件
![2016-10-28 13-27-48](https://cloud.githubusercontent.com/assets/13860006/19795881/6a6cef7e-9d12-11e6-901b-dc8b3fd42ca2.png)

> 在去除这一个带so文件得依赖之后，就不会出现此错误

**Comment by q757571446** [comment]
* 已找到问题原因，我依赖得so类库，arm、x86、mips，这三个平台都有，而weex得so只有一个，就会报错

**Comment by kevinTutu** [comment]
你好 我也遇到这个问题，但是我在集成sdk时并没有特别加入libweexv8.so依赖，请问楼主怎么解决的这个问题

**Comment by lovemyhan** [comment]
请问怎么解决的
