### ISSUE TITLE
WARNING: `display`,`border-top`.... is not a standard property name

### ISSUE THREAD

**Issue by zhouyuexie** [alibaba/weex#1590]
```shell
WARN ./index.we : WARNING: `display` is not a standard property name
WARN ./components/tabbar.we : WARNING: `transform-origin` is not a standard property name
./components/tab2.we : WARNING: `font-family` is not a standard property name
WARN ./~/weex-components/src/wxc-marquee.we : WARNING: `overflow` is not a standard property name
WARN ./~/weex-components/src/wxc-tabbar.we : WARNING: `visibility` is not a standard property name
```

I ran these months before the code output these warnings.

And then get this error :

```shell
2016-11-07 11:18 node[14763] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-07 11:18 node[14763] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-07 11:18 node[14763] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

Can someone help me?

**Comment by Jinjiang** [comment]
First, yes these code in Weex is not supported yet. Please have a look at the docs. Second, It seems a Node problem, please make sure your Node version is 4+ and the folder you run have enough permission to watch file changes.
Thanks.

**Comment by zhouyuexie** [comment]
@Jinjiang Thanks reply
