### ISSUE TITLE
安卓 BounceRecyclerView.setOnRefreshListener 空指针

### ISSUE THREAD

**Issue by wangweiqi23** [alibaba/weex#1710]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.taobao.weex.ui.view.refresh.wrapper.BounceRecyclerView.setOnRefreshListener(com.taobao.weex.ui.view.refresh.core.WXSwipeLayout$WXOnRefreshListener)' on a null object reference
                                                                    at com.taobao.weex.ui.component.list.WXListComponent.checkRefreshOrLoading(WXListComponent.java:678)
                                                                    at com.taobao.weex.ui.component.list.WXListComponent.addChild(WXListComponent.java:651)
                                                                    at com.taobao.weex.ui.component.list.WXListComponent.addChild(WXListComponent.java:637)
                                                                    at com.taobao.weex.ui.WXRenderStatement.generateComponentTree(WXRenderStatement.java:561)
                                                                    at com.taobao.weex.ui.WXRenderStatement.generateComponentTree(WXRenderStatement.java:561)
                                                                    at com.taobao.weex.ui.WXRenderStatement.createComponentOnDomThread(WXRenderStatement.java:373)
                                                                    at com.taobao.weex.ui.WXRenderManager.createComponentOnDomThread(WXRenderManager.java:351)
                                                                    at com.taobao.weex.dom.WXDomStatement.addDom(WXDomStatement.java:645)
                                                                    at com.taobao.weex.dom.WXDomManager.addDom(WXDomManager.java:356)
                                                                    at com.taobao.weex.dom.WXDomHandler.handleMessage(WXDomHandler.java:255)
                                                                    at com.taobao.weex.common.WXThread$SafeCallback.handleMessage(WXThread.java:258)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by wangweiqi23** [comment]
我的代码如下
> <template>
	<div class="root">
    <page-item id="pageItem" class="page-item" style="height:{{titleHeight}};" pages="{{sliderPages}}"></page-item>
    <slider style="width:750;height:{{channelHeight}};" index="{{currentIndex}}" append="tree" auto-play="false" onchange="onChange">
      <home-live-page style="width:750;height:{{channelHeight}};" repeat="{{sliderPages}}"></home-live-page>
    </slider>
  </div>  
</template>

home-live-page代码
> <list class="list">
    <refresh  class = "refresh-view" display="{{refresh_display}}" onrefresh="onrefresh">
      <text class="text-indicator" if="{{(refresh_display==='hide')}}"> ↓ 下拉刷新 </text>
      <loading-indicator class="indicator"></loading-indicator>
    </refresh>
    <cell class="cell" repeat="{{channelList}}">
      <channel-item class="item-left" channel="{{left}}" index="{{index}}"></channel-item></channel-item>
    </cell>
    <loading class="loading-view" display="{{loading_display}}" onloading="onloading">
      <text class="text-indicator" if="{{(loading_display==='hide')}}"> ↑ 上拉加载 </text>
      <loading-indicator class="indicator"></loading-indicator>
    </loading>
  </list>

**Comment by wangweiqi23** [comment]
请问这个有解决方案吗

**Comment by wangweiqi23** [comment]
看了源码 slider中组件componentTree构建不一样 可以改下list refresh 等相关组件
