### ISSUE TITLE
run app error ---out of memory 

### ISSUE THREAD

**Issue by spiritelf** [alibaba/weex#1713]
11-24 16:31:37.150 10590-10729/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:37.260 10590-10726/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:37.630 10590-10726/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:37.750 10590-10727/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:37.950 10590-10729/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:38.070 10590-10728/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:38.390 10590-10726/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:38.890 10590-10727/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:39.000 10590-10728/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:31:39.100 10590-10729/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:33:34.700 10590-10623/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 176516-byte allocation.
11-24 16:33:34.780 10590-11813/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 196234-byte allocation.
11-24 16:35:25.500 10590-10623/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 641462-byte allocation.
11-24 16:35:25.540 10590-10623/com.alibaba.weex E/SafeCallback: SafeCallback handleMessage throw expection:null
11-24 16:35:25.570 10590-10623/com.alibaba.weex E/AndroidRuntime: FATAL EXCEPTION: WeexJSBridgeThread
                                                                  java.lang.OutOfMemoryError
                                                                      at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:82)
                                                                      at java.lang.StringBuilder.<init>(StringBuilder.java:67)
                                                                      at com.taobao.weex.utils.WXFileUtils.loadAsset(WXFileUtils.java:232)
                                                                      at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1023)
                                                                      at com.taobao.weex.bridge.WXBridgeManager.invokeInitFramework(WXBridgeManager.java:1013)
                                                                      at com.taobao.weex.bridge.WXBridgeManager.handleMessage(WXBridgeManager.java:940)
                                                                      at com.taobao.weex.common.WXThread$SafeCallback.handleMessage(WXThread.java:258)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
11-24 16:35:40.550 17469-17469/com.alibaba.weex E/WXTBUtil: isSupportSmartBar:false
11-24 16:35:41.120 17469-17469/com.alibaba.weex E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-24 16:35:47.400 17469-17561/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:47.600 17469-17565/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:48.330 17469-17565/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:48.440 17469-17562/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:48.880 17469-17565/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:49.220 17469-17562/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:49.570 17469-17562/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:49.740 17469-17565/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:50.010 17469-17564/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:50.100 17469-17561/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:50.270 17469-17562/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:50.480 17469-17565/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:50.710 17469-17564/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.
11-24 16:35:50.820 17469-17561/com.alibaba.weex E/dalvikvm-heap: Out of memory on a 5548824-byte allocation.

**Comment by Hanks10100** [comment]
能否更详细的描述一下问题，你贴的这些信息好像看不出来什么。
