### ISSUE TITLE
android 分支 playground 扫描有crash

### ISSUE THREAD

**Issue by jiantao88** [alibaba/weex#1778]
```
11-30 10:34:55.091 19142-19142/com.alibaba.weex E/weex: add component failed.java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                            at java.util.ArrayList.get(ArrayList.java:413)
                                                            at com.taobao.weex.ui.component.WXVContainer.getChild(WXVContainer.java:390)
                                                            at com.taobao.weex.ui.component.list.WXListComponent.createChildViewAt(WXListComponent.java:704)
                                                            at com.taobao.weex.ui.WXRenderStatement.addComponent(WXRenderStatement.java:362)
                                                            at com.taobao.weex.ui.WXRenderManager.addComponent(WXRenderManager.java:361)
                                                            at com.taobao.weex.dom.WXDomStatement$AddDOMTask.execute(WXDomStatement.java:651)
                                                            at com.taobao.weex.ui.WXRenderManager$1.run(WXRenderManager.java:288)
                                                            at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                            at android.os.Looper.loop(Looper.java:154)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by misakuo** [comment]
请提供能复现crash的we文件内容

**Comment by Jinjiang** [comment]
由于长时间没有收到回复，这里先关掉了，再有新的情况可以重开或新开 issue
谢谢
