### ISSUE TITLE
macOS 下 weex hello.we 报错

### ISSUE THREAD

**Issue by jonahfang** [alibaba/weex#1978]
参照 https://github.com/weexteam/article/issues/109 文档开始首次体验 weex，但是：
执行weex hello.we总是报错：

```
2016-12-20 17:52 node[82467] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-20 17:52 node[82467] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-20 17:52 node[82467] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```
macOS版本为10.12.2,重新安装watchman(4.7.0)和node(v7.3.0)，都不能解决问题。
weex-toolkit用`cnpm install -g weex-toolkit`命令安装，版本为0.6.4.

**Comment by Jsnows** [comment]
我也遇到了相同的问题，node版本降到6.3.0也不行

**Comment by jonahfang** [comment]
查了google，好像和kern.maxfiles的值有关，我的命令'sudo launchctl limit'输出如下:

```
	cpu         unlimited      unlimited
	filesize    unlimited      unlimited
	data        unlimited      unlimited
	stack       8388608        67104768
	core        0              unlimited
	rss         unlimited      unlimited
	memlock     unlimited      unlimited
	maxproc     709            1064
	maxfiles    256            unlimited
```

没有找到有效地改变 maxfiles 设置的方法。

**Comment by jonahfang** [comment]
请查看这个问题，react-native-cli 也会报告类似错误: https://github.com/facebook/react-native/issues/10028

**Comment by appleandzfd** [comment]
同样遇到该问题，有木有最终解决方案呢

**Comment by jesusLove** [comment]
我之前遇到了，升级完Node就好了！

**Comment by jonahfang** [comment]
@jesusLove,请问升级后Node版本是多少？

**Comment by jonahfang** [comment]
同样的问题:https://github.com/weexteam/weex-toolkit/issues/34

**Comment by Jinjiang** [comment]
看起来是相同的问题，大家不介意的话在 weex-toolkit 的 issues 里继续讨论吧，为了让 issues 的内容更聚焦我这边先关掉了
感谢理解和支持

**Comment by jonahfang** [comment]
今天重新安装了weex-toolkit(版本还是0.6.4),这个问题没有再次出现。
node改用pkg包，版本为6.9.2; watchman 仍为v4.6.0; 为避免cnpm必须用sudo,执行了:

```
sudo chown -R $(whoami) /usr/local
```

**Comment by reason211** [comment]
表示和楼主一样的环境，还是不行。

**Comment by reason211** [comment]
info Wed Dec 28 2016 19:31:13 GMT+0800 (CST)WebSocket  is listening on port 8082
info Wed Dec 28 2016 19:31:13 GMT+0800 (CST)http  is listening on port 8081
2016-12-28 19:31 node[1019] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:31 node[1019] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:31 node[1019] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:31 node[1019] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:31 node[1019] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1012:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)

**Comment by exolution** [comment]
这个其实算是node-watch的bug 新macOS系统出现的情况比较多
基本原因是watch的文件太多或路径层级太深
建议把你的代码 放到一个纯净简单的目录下再执行 
如果实在不能解决我想办法加个nowatch的参数好了
