### ISSUE TITLE
[iOS] 组件中控制父级div的隐藏，子级div不跟着隐藏

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#2040]
我在组件中用：
foo.we
```javascript
<template>
    <div>
        <div if="shown">
             <div style="position:fixed;width:750;height:1400;background-color:rgba(0,0,0,.5)" onclick="hide"></div>
             <div style="position:fixed;width:750;height:800;background-color:#fff"><text>some child</text></div>
        </div>
    </div>
</template>
<script>
    module.exports = {
        data: {
            shown:false
        },
        created:function(){
            this.$on('showFoo', function (e) {
                this.shown = true
            }.bind(this));
        },
        methods:{
            hide:function(){
                this.shown=false;
            }
        }
</script>
```

iOS中，在父组件中调用`showFoo`显示正确，但是执行hide方法未能正常隐藏。
web端正常，安卓端未测

还有web端直接在template的子元素的第一个div使用`if=”shown”`也不能正常执行hide方法，所以写了两级div。是否是嵌套的shown的问题？

目前我是去掉了中间一级，给子元素都加了`if="shown"`后得到预期结果。

**Comment by Jinjiang** [comment]
template 第一个子元素是不能使用 if 或 repeat 的，这个文档里有交代过
不过这个例子确实有三端不一致的表现，我简单录了一个：http://dotwe.org/a6ce583afc8278d50870656aea86ee64
@cxfeng1 @sospartan 一块看一下吧
谢谢

**Comment by cxfeng1** [comment]
@dongnaebi  已确认为一个bug， fixed元素没有正确响应父元素的remove，可以暂时在fixed元素上加`if`来绕过， 我们会在下个版本修复

**Comment by Cstome** [comment]
android版的playground预览还是有这问题。

**Comment by hphua** [comment]
@cxfeng Android 0.10.0、weex-toolkit 1.0.3版本，使用fixed后，无法消失问题还没解决。

**Comment by hphua** [comment]
@cxfeng Android 0.10.0、weex-toolkit 1.0.3版本，使用fixed后，切换页面后，视图无法消失问题还没解决。

点击没消失视图区域，会引起崩溃。
```
java.lang.NullPointerException
 at com.taobao.weex.ui.component.WXRefresh.onPullingDown(WXRefresh.java:268)
 at com.taobao.weex.ui.view.refresh.core.WXSwipeLayout.moveSpinner(WXSwipeLayout.java:490)
```

```java 
@Override
  public void onPullingDown(float dy, int pullOutDistance, float viewHeight) {
    if (getDomObject().getEvents() != null && getDomObject().getEvents().contains(Constants.Event.ONPULLING_DOWN)) {
      Map<String, Object> data = new HashMap<>();
      data.put(Constants.Name.DISTANCE_Y, dy);
      data.put(Constants.Name.PULLING_DISTANCE, pullOutDistance);
      data.put(Constants.Name.VIEW_HEIGHT, viewHeight);
      fireEvent(Constants.Event.ONPULLING_DOWN, data);
    }
  }
```

**Comment by sospartan** [comment]
@hphua 我来跟进android的问题

**Comment by dongnaebi** [comment]
@sospartan 麻烦也看看这个[#2507](https://github.com/alibaba/weex/issues/2507)

**Comment by sospartan** [comment]
Fixed in https://github.com/apache/incubator-weex/pull/37 .

**Comment by hphua** [comment]
@sospartan 计划什么时候更新正式版SDK？
