### ISSUE TITLE
macos 10.12.2 无法运行weex的hello world，试了各种办法都没有什么效果（重装，重启）

### ISSUE THREAD

**Issue by reason211** [alibaba/weex#2060]
```
lvsendeMacBook:Desktop lvsen$ node -v
v6.3.1
lvsendeMacBook:Desktop lvsen$ npm -v
3.10.3
lvsendeMacBook:Desktop lvsen$ weex --version
info 0.6.4
lvsendeMacBook:Desktop lvsen$ wa
wait           wait4path      wall           watchman       watchman-make  watchman-wait
lvsendeMacBook:Desktop lvsen$ wa
wait           wait4path      wall           watchman       watchman-make  watchman-wait
lvsendeMacBook:Desktop lvsen$ watchman -v
4.6.0
lvsendeMacBook:Desktop lvsen$
lvsendeMacBook:Desktop lvsen$
lvsendeMacBook:Desktop lvsen$ ll test.we
-rwxrwxrwx  1 lvsen  staff    61B 12 28 17:37 test.we
lvsendeMacBook:Desktop lvsen$
lvsendeMacBook:Desktop lvsen$ weex test.we
info Wed Dec 28 2016 19:39:35 GMT+0800 (CST)WebSocket  is listening on port 8082
info Wed Dec 28 2016 19:39:35 GMT+0800 (CST)http  is listening on port 8081
2016-12-28 19:39 node[3205] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:39 node[3205] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:39 node[3205] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:39 node[3205] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:39 node[3205] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-28 19:39 node[3205] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1012:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

**Comment by exolution** [comment]
这个其实算是node-watch的bug 新macOS系统出现的情况比较多
基本原因是watch的文件太多或路径层级太深 （大多数的原因是we当前目录下有很多别的文件 特别是node_modules 这种恐怖的文件目录）
建议把你的代码 放到一个纯净简单的目录下再执行 
如果实在不能解决我想办法加个nowatch的参数好了

**Comment by reason211** [comment]
非常感谢！！
当前目录下确实很多别的目录，我试试看移到某个独立的文件夹里
