### ISSUE TITLE
Andorid【Bug】WXWebView销毁bug

### ISSUE THREAD

**Issue by samyzh** [alibaba/weex#2072]
E/webview: java.lang.Throwable: Error: WebView.destroy() called while still attached!
                                                                   at android.webkit.WebViewClassic.destroy(WebViewClassic.java:2479)
                                                                   at android.webkit.WebView.destroy(WebView.java:654)
                                                                   at com.taobao.weex.ui.view.WXWebView.destroy(WXWebView.java:271)
                                                                   at com.taobao.weex.ui.component.WXWeb.destroy(WXWeb.java:287)
                                                                   at com.taobao.weex.ui.component.WXVContainer.destroy(WXVContainer.java:317)
                                                                   at com.taobao.weex.ui.component.WXVContainer.destroy(WXVContainer.java:317)
                                                                   at com.taobao.weex.ui.component.WXVContainer.destroy(WXVContainer.java:317)
                                                                   at com.taobao.weex.ui.component.WXVContainer.destroy(WXVContainer.java:317)
                                                                   at com.taobao.weex.ui.WXRenderStatement.destroy(WXRenderStatement.java:261)
                                                                   at com.taobao.weex.ui.WXRenderManager.removeRenderStatement(WXRenderManager.java:273)
                                                                   at com.taobao.weex.WXSDKManager.destroyInstance(WXSDKManager.java:293)
                                                                   at com.taobao.weex.WXSDKInstance.destroy(WXSDKInstance.java:939)
                                                                   at com.taobao.weex.WXSDKInstance.onActivityDestroy(WXSDKInstance.java:705)
应先：
ViewGroup parent = (ViewGroup) mWebView.getParent();
      if (parent != null) {
        parent.removeView(mWebView);
      }
 getWebView().removeAllViews();
            getWebView().destroy();
            mWebView = null;

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
