### ISSUE TITLE
[Android] Weex SDK 初始化报错。

### ISSUE THREAD

**Issue by CCC2016** [alibaba/weex#2327]
版本 android 0.9.5；

``` Text
01-19 10:11:29.880 5863-5863/com.android.app:remote E/weex: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.taobao.weex.utils.WXHack$HackedConstructor.getInstance(WXHack.java:487)
    at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:371)
    at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:342)
    at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:351)
    at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:258)
    at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:247)
    at com.android.app.MyApplication.onCreate(MyApplication.java:83)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4589)
    at android.app.ActivityThread.access$1500(ActivityThread.java:155)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5426)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.taobao.weex.devtools.common.Util.throwIfNull(Util.java:26)
    at com.taobao.weex.devtools.inspector.jsonrpc.JsonRpcPeer.<init>(JsonRpcPeer.java:44)
    at com.taobao.weex.devtools.debug.DebugServerProxy.<init>(DebugServerProxy.java:60)
    at java.lang.reflect.Constructor.constructNative(Native Method) 
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
    at com.taobao.weex.utils.WXHack$HackedConstructor.getInstance(WXHack.java:487) 
    at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:371) 
    at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:342) 
    at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:351) 
    at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:258) 
    at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:247) 
    at com.android.app.MyApplication.onCreate(MyApplication.java:83) 
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4589) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5426) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
    at dalvik.system.NativeStart.main(Native Method) 
```
指向的是 `WXSDKEngine.initialize(this, weexConfig);`

**Comment by CCC2016** [comment]
`java.io.FileNotFoundException`
设备机型：OPPO A53；
系统版本：Android 5.1.1,level 22；

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.android.app/com.android.app.splash.SplashActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052

**Comment by markzhai** [comment]
也碰到了：

01-22 00:34:46.828 2757-2757/cn.bigins.hmb E/weex: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                       at com.taobao.weex.utils.WXHack$HackedConstructor.getInstance(WXHack.java:487)
                                                       at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:371)
                                                       at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:342)
                                                       at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:351)
                                                       at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:258)
                                                       at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:247)
                                                       at cn.bigins.module.product.WXApplication.onCreate(WXApplication.java:23)
                                                       at cn.bigins.hmb.HmbbApplication.onCreate(HmbbApplication.java:12)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.NullPointerException
                                                       at com.taobao.weex.devtools.common.Util.throwIfNull(Util.java:26)
                                                       at com.taobao.weex.devtools.inspector.jsonrpc.JsonRpcPeer.<init>(JsonRpcPeer.java:44)
                                                       at com.taobao.weex.devtools.debug.DebugServerProxy.<init>(DebugServerProxy.java:60)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                       at com.taobao.weex.utils.WXHack$HackedConstructor.getInstance(WXHack.java:487) 
                                                       at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:371) 
                                                       at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:342) 
                                                       at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:351) 
                                                       at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:258) 
                                                       at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:247) 
                                                       at cn.bigins.module.product.WXApplication.onCreate(WXApplication.java:23) 
                                                       at cn.bigins.hmb.HmbbApplication.onCreate(HmbbApplication.java:12) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by weiyideai520** [comment]
compile 'com.taobao.android:weex_sdk:0.9.4'
    compile 'com.taobao.android:weex_inspector:0.10.0.5' 一样的

**Comment by CCC2016** [comment]
``` grovver
compile 'com.taobao.android:weex_sdk:0.9.5'
compile 'com.taobao.android:weex_inspector:0.10.0.5'
compile 'com.alibaba:fastjson:1.1.56.android'
compile 'com.facebook.fresco:fresco:1.0.0'
```
版本还是安卓 0.9.5，新建的项目运行没有出错；
不知是不是这个问题导致的 [#2333](https://github.com/alibaba/weex/issues/2333)
报错的项目确实集成了 **multidex**
`compile 'com.android.support:multidex:1.0.1'`

**Comment by CCC2016** [comment]
``` groovy
compile 'com.taobao.android:weex_sdk:0.9.5'
compile 'com.taobao.android:weex_inspector:0.10.0.5'
compile 'com.alibaba:fastjson:1.1.56.android'
compile 'com.facebook.fresco:fresco:1.0.0'
```
Weex 的代码没有修改，现在初始化又正常了。😂

**Comment by wuchengithub** [comment]
不知道是不是和我开启了debug有关系，

 Caused by: java.lang.NullPointerException
                                                             at com.taobao.weex.devtools.common.Util.throwIfNull(Util.java:26)
                                                             at com.taobao.weex.devtools.inspector.jsonrpc.JsonRpcPeer.<init>(JsonRpcPeer.java:44)
                                                             at com.taobao.weex.devtools.debug.DebugServerProxy.<init>(DebugServerProxy.java:60)
                                                             at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                                                             at com.taobao.weex.utils.WXHack$HackedConstructor.getInstance(WXHack.java:487) 
                                                             at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:373) 
                                                             at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:344) 
                                                             at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:353) 
                                                             at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:259) 
                                                             at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:248) 
                                                             at com.wookii.weexdemo.WXApplication.onCreate(WXApplication.java:24) 
                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                             at android.os.Looper.loop(Looper.java:164) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
