### ISSUE TITLE
在7.0中，打开demo中的Hello World页面直接崩溃

### ISSUE THREAD

**Issue by myth2loki** [alibaba/weex#2332]
在7.0中，打开demo中的Hello World页面直接崩溃，应该是7.0的限制，导致startActivity不能直接用

Caused by: android.os.FileUriExposedException: file://assets/hello.js exposed beyond app through Intent.getData()
                                                                                 at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                                 at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                                 at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
                                                                                 at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                                                                                 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                                                                                 at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                                 at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                                 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                                 at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                                 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                                 at android.app.Activity.startActivity(Activity.java:4507)
                                                                                 at android.app.Activity.startActivity(Activity.java:4475)
                                                                                 at com.alibaba.weex.extend.module.WXEventModule.openURL(WXEventModule.java:39)
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:232) 
                                                                                 at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:234) 
                                                                                 at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by CCC2016** [comment]
7.0 进行了权限更高
https://developer.android.google.cn/about/versions/nougat/android-7.0-changes.html#perm

我碰到了显示空白，不渲染界面问题 [#2252](https://github.com/alibaba/weex/issues/2252)

**Comment by myth2loki** [comment]
@CCC2016 我将activity跳转改为显式就可使用了，不知道weex后续更新会怎么处理这个问题@CCC2016 我将activity跳转改为显式就可使用了，不知道weex后续更新会怎么处理这个问题

**Comment by mengyubo** [comment]
marker 求解决，遇到同样问题，目前只能讲解安卓版本了

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
