### ISSUE TITLE
macOS安装weex-toolkit@beta报错

### ISSUE THREAD

**Issue by cainiaoer** [alibaba/weex#2404]
在macOS上执行这个命令报错：
`sudo cnpm install -g weex-toolkit@beta`
按照快速上手上面的教程，前面安装都没问题，就到这里出问题了

`scripts.postinstall weex-toolkit@1.0.1-beta.5 run "xtoolkit install weex-builder"
/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.1.7@xtoolkit/src/util/index.js:8
    let args = ['install', name, '--loglevel=error'];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.1.7@xtoolkit/bin/xtoolkit.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Error: post install error, please remove node_modules before retry!
Run "sh -c xtoolkit install weex-builder" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npminstall version: 2.17.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/kang/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org -g weex-toolkit@beta`

**Comment by dancancer** [comment]
seem problem

**Comment by DoranYun** [comment]
升级 node 版本到 6.0 以上试试。

**Comment by cainiaoer** [comment]
@DoranYun 感谢，就是版本问题，之前电脑上装过一个5系列版本的，升级了下就好了

**Comment by DoranYun** [comment]
@cainiaoer 🤝
那我就先 close 了。

**Comment by youmu178** [comment]
用这些命令升级了node  怎么还是原来的版本啊，你们用的什么命令
npm cache clean -f
npm install -g n
n stable

**Comment by 452MJ** [comment]
Is anybody solve this?

**Comment by sadaharusong** [comment]
@452MJ update node to version 6.0+
