### ISSUE TITLE
android Textarea

### ISSUE THREAD

**Issue by gxmdboy** [alibaba/weex#2470]
android 系统：4.4.4
weex sdk :0.9.5
手机型号：oppo R8

在Textarea里输入大量文字后，再次点击文字时，只有箭头无光标，再次点击箭头时crash
报错日志：
```
02-08 11:54:49.958 4264-4264/com.ucmed.testapp E/Parcel: Reading a NULL string not supported here.
02-08 11:54:51.028 4264-4264/com.ucmed.testapp E/InputEventReceiver: Exception dispatching input event.
02-08 11:54:51.028 4264-4264/com.ucmed.testapp E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
02-08 11:54:51.028 4264-4264/com.ucmed.testapp E/MessageQueue-JNI: java.lang.NullPointerException
                                                                       at android.widget.OppoCursorController$InsertionPointCursorController.showInsertionPanel(OppoCursorController.java:326)
                                                                       at android.widget.OppoCursorController$InsertionPointCursorController.onHandleTouchEvent(OppoCursorController.java:313)
                                                                       at android.widget.OppoCursorController$OppoHandleView.onTouchEvent(OppoCursorController.java:1040)
                                                                       at android.widget.OppoCursorController$InsertionHandleView.onTouchEvent(OppoCursorController.java:1166)
                                                                       at android.view.View.dispatchTouchEvent(View.java:7706)
                                                                       at android.view.View.dispatchPointerEvent(View.java:7886)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4045)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3561)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3618)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3419)
                                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5636)
                                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5616)
                                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5587)
                                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5725)
                                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:195)
                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                       at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                       at android.os.Looper.loop(Looper.java:123)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5120)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```
截图：
![screenshot_2017-02-08-11-50-19-414](https://cloud.githubusercontent.com/assets/13041525/22723363/9adb9304-edf8-11e6-9ba8-e064b3b6bee4.png)

再次点击绿色箭头crash

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
