### ISSUE TITLE
Android，引入weex时报异常；

### ISSUE THREAD

**Issue by yuwei2589** [alibaba/weex#2585]
我遇到了一个错误的提示,环境如下,请帮忙看一下，每次都出现；
androidStudio version: 2.2.2
android os: 6.0
npm version:3.10.10
weex version：info 1.0.1-alpha
node version: V6.9.5

关键代码：
 public class xxApplication extends Application{
     .....
       try {
            //weex引入初始化
            InitConfig config=new InitConfig.Builder().setImgAdapter(new ImageAdapter()).build();
            WXSDKEngine.initialize(this,config);
        } catch (Exception e) {
            e.printStackTrace();
        }
}

02-15 18:07:49.324 com.xingyun.main E/weex: initWXBridge HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
                                                at com.taobao.weex.utils.WXHack.into(WXHack.java:232)
                                                at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:369)
                                                at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:342)
                                                at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:351)
                                                at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:258)
                                                at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:247)
                                                at com.xingyun.application.XYApplication.onCreate(XYApplication.java:96)
                                                at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5127)
                                                at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1633)
                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                at android.os.Looper.loop(Looper.java:207)
                                                at android.app.ActivityThread.main(ActivityThread.java:5896)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                             Caused by: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
                                                at java.lang.Class.classForName(Native Method)
                                                at java.lang.Class.forName(Class.java:324)
                                                at java.lang.Class.forName(Class.java:285)
                                                at com.taobao.weex.utils.WXHack.into(WXHack.java:230)
                                                at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:369) 
                                                at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:342) 
                                                at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:351) 
                                                at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:258) 
                                                at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:247) 
                                                at com.xingyun.application.XYApplication.onCreate(XYApplication.java:96) 
                                                at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370) 
                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018) 
                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5127) 
                                                at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1633) 
                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                at android.os.Looper.loop(Looper.java:207) 
                                                at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.devtools.debug.DebugServerProxy" on path: DexPathList[[dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-wup-1.0.0.E-SNAPSHOT_9c04812cc434eecaed454e2b396bff4e275099ec-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-weibosdkcore_release_e186a54df134b3b3d935e5ee53d7d25e67c42267-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-support-annotations-23.1.0_4e432569f42e5f0a6e5385af8741ebcfe05ac3a8-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-stream-1.1.1_7283a057326cb28998d677b1dce61f28c2bc7825-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-rxjava-1.1.9_c00d817c7cdf7a2513a7cba5178b605e0c3be9b9-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-ormlite-core-4.48_c3209f572c4a4f0b2d6b8d6e11a8d444a44dd4c7-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-ormlite-android-4.48_9eb1fefbda64732ff1ec9740738e664d3195673c-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-open_sdk_r5756_e3a6cbbe06fbd3367e8e5a1bfa9d2da238bfd358-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-okio-1.9.0_b2f9dd1df4c40329655c512f2a8a2219c0a56e61-classes.dex", dex file "/data/data/com.xingyun.main/files/instant-run/dex/slice-ok

**Comment by fenglincanyi** [comment]
我也遇到了这个问题

**Comment by AllenVork** [comment]
同问

**Comment by shangcongrong** [comment]
应该是少加了一些依赖，你可以排查下自己都加全了吗

compile 'com.android.support:recyclerview-v7:23.1.1'
compile 'com.android.support:support-v4:23.1.1'
compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.alibaba:fastjson:1.1.46.android'
compile 'com.taobao.android:weex_sdk:0.5.1@aar'

**Comment by AllenVork** [comment]
依赖全了。日志看起来是少了debug依赖。

发自我的 iPhone

**Comment by yesong** [comment]
我也遇到这个问题 使用demo里的 debug.keystore可以正常显示weex页面

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
