### ISSUE TITLE
Weexpack创建应用失败

### ISSUE THREAD

**Issue by DoubleDa** [alibaba/weex#2597]
使用weex开发套件weexpack创建应用时出现这个问题，该如何解决呢？求解
$ weexpack create app
/usr/local/lib/node_modules/weexpack/src/publish/market.js:16
let marketEnv = 'online';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack:5:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

**Comment by exolution** [comment]
请升级你的node
weexpack 需要node6.0以上
建议升级至官方的长效稳定版本 6.9.x 
(4.x官方都不维护了)
