### ISSUE TITLE
Devtools 使用时提示没安装weex-devtool，但是我安装了weex-toolkit，难道devtool不包含在内么？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2654]
我安装了weex-toolkit ,并且安装成功了命令是：

`npm install -g weex-toolkit@beta`

但是通过命令行 weex debug 使用devtool的时候，提示我没安装weex-devtool。

`This command need to install weex-devtool ,Install now?Y/n`
选了yes之后提示：

{ AssertionError: path must be a string
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at Command.immediateStart (C:\Users\xinyang\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\src\Command.js:49:9)
    at Locator.getInstance.locate.then (C:\Users\xinyang\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\src\Command.js:30:29)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'path must be a string',
  generatedMessage: false }
AssertionError: path must be a string
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at Command.immediateStart (C:\Users\xinyang\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\src\Command.js:49:9)
    at Locator.getInstance.locate.then (C:\Users\xinyang\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\src\Command.js:30:29)

**Comment by wxxcarl** [comment]
同问！

**Comment by willzhai** [comment]
同问，有解决方法吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
