### ISSUE TITLE
出现Crash，望修复

### ISSUE THREAD

**Issue by harvic** [alibaba/weex#2792]
java.lang.NullPointerException
at com.taobao.weex.utils.WXViewUtils.getScreenWidth(SourceFile:311)
at com.taobao.weex.http.WXHttpUtil.assembleUserAgent(SourceFile:225)
at com.taobao.weex.WXSDKInstance.renderByUrl(SourceFile:515)
at fm.xiami.main.weex.WeexRenderProxy.render(SourceFile:131)
at fm.xiami.main.weex.WeexContainerFragment.renderPolicy(SourceFile:294)
at fm.xiami.main.weex.WeexContainerFragment.loadWeexFile(SourceFile:280)
at fm.xiami.main.weex.WeexContainerFragment$2.onGlobalLayout(SourceFile:218)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:815)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1785)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5718)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:544)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5120)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
at dalvik.system.NativeStart.main(Native Method)
Back traces end.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
