### ISSUE TITLE
libweexv8bk1.so is 32-bit instead of 64-bit？？？

### ISSUE THREAD

**Issue by xiaoqi951109** [alibaba/weex#2803]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.example.test/files/libweexv8bk1.so" is 32-bit instead of 64-bit
                                                                  at java.lang.Runtime.load(Runtime.java:332)
                                                                  at java.lang.System.load(System.java:1069)
                                                                  at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:444)
                                                                  at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:309)
                                                                  at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:270)
                                                                  at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:168)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
