### ISSUE TITLE
安卓position:fixed问题，跳转页面，fixed元素依然在不会消失

### ISSUE THREAD

**Issue by lehahagirl** [alibaba/weex#2969]
安卓fixed元素跳转页面无法消失，请问应如何解决？

**Comment by vfasky** [comment]
https://github.com/MMF-FE/weex-vue-fixed/blob/master/README-CN.md

**Comment by lehahagirl** [comment]
@vfasky 我看到这个了，也安装了这个，但是安装完之后我的项目就不能编译了，npm run build不成功。这个怎么办

**Comment by vfasky** [comment]
报错信息是什么？

**Comment by lehahagirl** [comment]
> douban@1.0.0 build /Users/ikicker-010/git/Weex-Court
> webpack

/Users/ikicker-010/git/Weex-Court/node_modules/webpack/lib/BannerPlugin.js:19
			throw new Error("BannerPlugin only takes one argument (pass an options object)");
			^

Error: BannerPlugin only takes one argument (pass an options object)
    at new BannerPlugin (/Users/ikicker-010/git/Weex-Court/node_modules/webpack/lib/BannerPlugin.js:19:10)
    at Object.<anonymous> (/Users/ikicker-010/git/Weex-Court/webpack.config.js:4:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/ikicker-010/git/Weex-Court/node_modules/webpack/bin/convert-argv.js:96:18)

**Comment by vfasky** [comment]
你这个报错， 应该跟 webpack.config.js 的第4行代码有关。
好像跟 `weex-vue-fixed` 没有关系

**Comment by lehahagirl** [comment]
我这个主要是用在下面的tabbar，我用fixed安卓就会出问题，后来我看到一个例子，是用导航和tabbar正常些，然后中间是scroller给一个固定高度，这样就会造成导航和tabbar固定的样子。可是中间的高度因为手机型号太多，所以有的手机会有一个空白的小边，空隙。我想问问你的tabbar是怎么设置的

**Comment by vfasky** [comment]
参考这个 https://github.com/weexteam/weex-components/blob/master/src/wxc-tabbar.we

**Comment by lehahagirl** [comment]
他这不是用fixed的吗。除了这个还有吗

**Comment by beghujam** [comment]
@vfasky  上面你给的是we文件的   有vue文件的吗
