### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_773e439/Offline

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#3036]
android studio 3.0 preview报这个错。 之前用2.3没问题。怎么办

FATAL EXCEPTION: main
                                                   Process: com.kiway.yjpt.Teacher, PID: 26887
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_773e439/Offline;
                                                       at com.taobao.weex.InitConfig$Builder.$jacocoInit(InitConfig.java)
                                                       at com.taobao.weex.InitConfig$Builder.<init>(InitConfig.java)
                                                       at com.zk.myweex.WXApplication.onCreate(WXApplication.java:82)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_773e439.Offline" on path: DexPathList[[zip file "/data/app/com.kiway.yjpt.Teacher-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kiway.yjpt.Teacher-1/lib/arm, /data/app/com.kiway.yjpt.Teacher-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at com.taobao.weex.InitConfig$Builder.$jacocoInit(InitConfig.java) 
                                                       at com.taobao.weex.InitConfig$Builder.<init>(InitConfig.java) 
                                                       at com.zk.myweex.WXApplication.onCreate(WXApplication.java:82) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                   	Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_773e439.Offline
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 14 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by haoma2012** [comment]
no people to resove this question?

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
