### ISSUE TITLE
按照提示升级到最新weex devtool，运行weex debug报错！！ 没办法继续了。。

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex#3071]
C:\weex-asf-0.12.0\>weex debug
module.js:472
    throw err;
    ^

Error: Cannot find module '../lib/DebugServer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\zhouhongen\.xtoolkit\node_modules\weex-devtool\bin\weex-devtool.
js:12:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by 501956430** [comment]
更新后同样遇到 坑呀

**Comment by 501956430** [comment]
重新更新 weex-devtool 就好了

**Comment by alex1226** [comment]
weex debug再按照提示升级到最新0.2.82版本就好了 谢谢
