### ISSUE TITLE
android 7.0   E/Navigator: android.os.FileUriExposedException: file://assets/goodDetail.js exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by hustliweizeng** [alibaba/weex#3119]
android 高版本执行navigator跳转页面时报异常：E/Navigator: android.os.FileUriExposedException: file://assets/goodDetail.js exposed beyond app through Intent.getData()
低版本不存在问题，应该是需要在mainfest注册provider授予权限等，官方有没有详细的解决方法？

**Comment by xiaonanhailili** [comment]
Android 7.0 以上就需要了 但是注册provider授予权限出现以下情况

E/Navigator: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[包名] dat=content://包名.fileprovider/cache/pages/*.js flg=0x2 (has extras) }
贼恐怖

**Comment by dingyanyi** [comment]
StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
    StrictMode.setVmPolicy(builder.build());
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
      builder.detectFileUriExposure();
    }

**Comment by dingyanyi** [comment]
我是采用这种方法解决的 
 StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
    StrictMode.setVmPolicy(builder.build());
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
      builder.detectFileUriExposure();
    }

**Comment by xiaonanhailili** [comment]
@dingyanyi 我是这样解决的:将file://转换为http,再转换回来
![image](https://user-images.githubusercontent.com/13197336/35077857-30006978-fc3a-11e7-997c-ecda545d9638.png)

**Comment by heiren0926** [comment]
大哥们，俺是安卓小白，能说的详细点吗？到底咋解决的啊？

**Comment by QzwJuHao** [comment]
在你的Application中添加：
   if (Build.VERSION.SDK_INT>=18) {
      StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
      StrictMode.setVmPolicy(builder.build());
      builder.detectFileUriExposure();
    }

**Comment by guojinlong1** [comment]
大哥们，我把这段话放在Application中不管用啊，求助，谢谢啦

**Comment by guojinlong1** [comment]
大哥们，这几行放进Application还是不行，求助各位，谢谢啦

**Comment by guojinlong1** [comment]
我是按照您说的那么写的，这个方法也执行了，可时跳转的时候还是报出了FileUriExposedException（我是放在onCreate()方法里的）

**Comment by QzwJuHao** [comment]
你确定在mainifests中修改了你的Application的名字了么
@guojinlong1

**Comment by guojinlong1** [comment]
嗯，确定！我在Application中写了log,控制台也打出来了

**Comment by QzwJuHao** [comment]
@guojinlong1 
我每次使用都是没有问题的，我也没法看到你的代码，不好意思不能帮你了。
这个问题是Android原生的问题，与weex其实没关系。
不过你可以尝试谷歌推荐的方法，稍微麻烦一点。使用FileProvider生成content:// Uri来替代file:// Uri，搜一下网上有很多。

**Comment by guojinlong1** [comment]
@QzwJuHao 嗯嗯！谢谢您啦

**Comment by QzwJuHao** [comment]
you are welcome
@guojinlong1

**Comment by guojinlong1** [comment]
@QzwJuHao 刚刚重启了一下电脑，发现那个问题没了，但是却报出了android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[com.taobao.android.intent.category.WEEX] dat=file://assets/dist/search.js (has extras) }问题，请问您遇到过么

**Comment by guojinlong1** [comment]
@QzwJuHao 解决了，麻烦您了，谢谢您

**Comment by QzwJuHao** [comment]
嗯嗯
@guojinlong1

**Comment by yangdm2015** [comment]
我使用官方的weex create工具创建的工程，使用navigator跳转页报这个FileUriExposedException错，看了上面的讨论，在继承了Application类的WXApplication类的onCreate方法里加了一下三行代码
`StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
        StrictMode.setVmPolicy(builder.build());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            builder.detectFileUriExposure();
        }`
加完之后这个类长这样：
`public class WXApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        WXSDKEngine.addCustomOptions("appName", "WXSample");
        WXSDKEngine.addCustomOptions("appGroup", "WXApp");
        WXSDKEngine.initialize(this,
                new InitConfig.Builder().setImgAdapter(new ImageAdapter()).build()
        );


        StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
        StrictMode.setVmPolicy(builder.build());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            builder.detectFileUriExposure();
        }


        try {
            WXSDKEngine.registerModule("event", WXEventModule.class);
        } catch (WXException e) {
            e.printStackTrace();
        }
        AppConfig.init(this);
        WeexPluginContainer.loadAll(this);
    }
}
`
这下跳转倒是不报错了，但是跳转时一直转圈，页面不动了。我是前端转来做weex的，不懂啊。哪位大神能给讲讲？
奇怪的是我从android studio打开，调转时就会出现这个情况。但在工程里直接运行 npm run android，就不会有这个问题。

**Comment by hxgqh** [comment]
@QzwJuHao 按照您的配置，仍然存在问题：

```
05-26 20:35:26.420 31126 31126 W weex    : Warning :Component tree has not build completely,onActivityCreate can not be call!
05-26 20:35:26.425 31126 31126 W System.err: org.json.JSONException: Value file of type java.lang.String cannot be converted to JSONObject
05-26 20:35:26.425 31126 31126 W System.err: 	at org.json.JSON.typeMismatch(JSON.java:111)
05-26 20:35:26.426 31126 31126 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:160)
05-26 20:35:26.426 31126 31126 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:173)
05-26 20:35:26.426 31126 31126 W System.err: 	at com.weex.app.WXPageActivity.onCreate(WXPageActivity.java:67)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.Activity.performCreate(Activity.java:6662)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.os.Looper.loop(Looper.java:154)
05-26 20:35:26.426 31126 31126 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
05-26 20:35:26.426 31126 31126 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-26 20:35:26.426 31126 31126 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
05-26 20:35:26.426 31126 31126 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
05-26 20:35:26.428 31126 31126 E WXTBUtil: isSupportSmartBar:false

```

**Comment by burro630** [comment]
有结局办法吗

**Comment by burro630** [comment]
有统一处理办法吗 各位

**Comment by gdoudeng** [comment]
在application加完那几行代码后又报这样的错了
`[WXModalUIModule] alert param parse error java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference`

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
