### ISSUE TITLE
Android Build Fails on OSX 10.13.1

### ISSUE THREAD

**Issue by 34r7h** [alibaba/weex#3123]
io:~ i$ sudo weex build android
```
Last login: Thu Nov 23 14:40:57 on ttys005
/Users/i/Apps/iic/weex-cool/cool/start ; exit;
io:~ i$ /Users/i/Apps/iic/weex-cool/cool/start ; exit;
*****************************************************************************
*                             Welcome to Weex                               *
*                                                                           *
*             A framework for building Mobile cross-platform UI.            *
*                                                                           *
*                      https://github.com/alibaba/weex                      *
*****************************************************************************
~/Apps/iic/weex-cool/cool ~

> weex@1.0.0 serve /Users/i/Apps/iic/weex-cool/cool
> webpack-dev-server --config webpack.dev.js --watch --open

server is running! Please open http://192.168.1.23:8080/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weex@1.0.0 serve: `webpack-dev-server --config webpack.dev.js --watch --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weex@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
~
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by UEDNewbie** [comment]
同上

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
