### ISSUE TITLE
 Unsupported URL Type: npm:string-width@^4.2.0

### ISSUE THREAD

**Issue by muniana** [alibaba/weex#3351]
weex preview报错：
× Install fail! Error: Unsupported URL Type: npm:string-width@^4.2.0
Error: Unsupported URL Type: npm:string-width@^4.2.0
    at parseUrl (C:\Users\h\.wx\core\node_modules\_npm-package-arg@4.2.1@npm-package-arg\npa.js:186:13)
    at npa (C:\Users\h\.wx\core\node_modules\_npm-package-arg@4.2.1@npm-package-arg\npa.js:79:12)
    at _install (C:\Users\h\.wx\core\node_modules\_npminstall@3.28.1@npminstall\lib\install.js:62:11)
    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\h\.wx\core\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\h\.wx\core\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\h\.wx\core\node_modules\_co@4.6.0@co\index.js:50:10)
    at toPromise (C:\Users\h\.wx\core\node_modules\_co@4.6.0@co\index.js:118:63)
    at next (C:\Users\h\.wx\core\node_modules\_co@4.6.0@co\index.js:99:29)

**Comment by aa-cmd** [comment]
I've come across with same issue w/ node@8.9.4, npm@5.6.0

**Comment by fjcondy** [comment]
me too. node version: v14.21.3.  npm@6.14.18 . Mac platform.
`weex install @weex-cli/compile --registry=https://registry.npmmirror.com
✖ Install fail! Error: Unsupported URL Type: npm:string-width@^4.2.0
Error: Unsupported URL Type: npm:string-width@^4.2.0`

can somebody help me !

**Comment by firekyrin** [comment]
来信收悉，非常感谢！============http://www.firekyrin.com

**Comment by fjcondy** [comment]
找到问题了，需要把@weex-cli重装，

**Comment by cloud-jie** [comment]
我有同样的问题：

node ：v22.14.0
npm  ：11.2.0

重装 weex 重装，问题依旧

**Comment by firekyrin** [comment]
来信收悉，非常感谢！============http://www.firekyrin.com
