### ISSUE TITLE
WebStorm weex插件报错

### ISSUE THREAD

**Issue by fengshanjian** [alibaba/weex#767]
如题
除了一下的报错，还有就是weex的配置中的weexPath的配置有问题，需要配置成weex/node_modules/weex-loader
才不会报local build path is invalid的错误

javafx/application/Platform
java.lang.NoClassDefFoundError: javafx/application/Platform
	at com.darin.weex.ui.preview.WeexFxPreviewEditor$2$1.run(WeexFxPreviewEditor.java:161)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)

上述问题是由于自己storm的jdk版本导致的

但是还是会报错，且语法高亮还是没有
不知道是不是我使用的方式不对

会报错 the custom element wxc-tabbar is not found /User/***

**Comment by fengshanjian** [comment]
没人回答，自己查了下，改了下webstorm的jdk，不再报这个错了，但是还是不能像介绍的那样工作😓

**Comment by luics** [comment]
@gurisxie

**Comment by Darin726** [comment]
**语法高亮目前正在开发中**大概在八月份会支持这个功能

transformer 对应的目录发生了变化,所以现在无法 transform weex文件, 我一会更新一下版本修复一下这个问题

**Comment by Darin726** [comment]
这个 bug 已经修改好, 如有要我可以发送一个本地版本到你邮箱里.

另外, 你可以先将 weex 文件绑定为 html 或者 JavaScript, 这样就会有语法提示了,如图所示
![snip20160713_13](https://cloud.githubusercontent.com/assets/4989836/16808540/7ffc6d90-494f-11e6-837a-ea3b9a844cfc.png)

**Comment by fengshanjian** [comment]
多谢@Darin726

**Comment by dodola** [comment]
@Darin726 插件的现在是开源的么？

**Comment by Darin726** [comment]
还没有呢, 目前还正出去开发阶段,等基本功能完善好了再进行开源

**Comment by davidmoshal** [comment]
Hi, trying to set up the plugin, wondering what `weexpath` should be set to?

**Comment by Darin726** [comment]
@davidmoshal The `weexPath` is the path that you clone the repository of [Weex](https://github.com/alibaba/weex).  Before you set it you should have installed the [Node.js](https://nodejs.org/en/) and excuted `npm install ` under the `weex` project path

**Comment by davidmoshal** [comment]
thanks!
