### ISSUE TITLE
第一次安装sudo cnpm install -g weex-toolkit 有报错

### ISSUE THREAD

**Issue by yubhbh** [alibaba/weex#801]
第一次安装sudo cnpm install -g weex-toolkit 有报错。
node version :  6.3.0
mac version: 10.11.2

-----------------------------------------------
 sh: node-gyp: command not found
[Error: Run "sh -c node-gyp rebuild" error, exit code 127
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)@%s] optional error: %s

重新安装  sudo cnpm install -g node-gyp， 之后
再安装sudo cnpm install -g weex-toolkit 问题解决。

小问题，对于开发的体验和阿里的专业精神，建议解决掉。

**Comment by lvscar** [comment]
谢谢， 我们后续看看能不能自动化安装 node-gyp 或在文档中增加提示.

**Comment by lvscar** [comment]
新版本[weex-toolkit](https://www.npmjs.com/package/weex-toolkit)  文档Pre Install章节添加了检查并安装 node-gyp 的提示.
