### ISSUE TITLE
[Bug]playground 扫码调试crash

### ISSUE THREAD

**Issue by 750813987** [alibaba/weex#874]
![playground](https://cloud.githubusercontent.com/assets/19163532/17163226/aa01c2e8-53ef-11e6-91f6-12b3821ae2e7.png)
```java
5872/com.alibaba.weex E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                Process: com.alibaba.weex, PID: 5572
                                                                java.lang.SecurityException: getDeviceId: Neither user 10076 nor current process has android.permission.READ_PHONE_STATE.
                                                                    at android.os.Parcel.readException(Parcel.java:1620)
                                                                    at android.os.Parcel.readException(Parcel.java:1573)
                                                                    at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4207)
                                                                    at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:746)
                                                                    at com.taobao.weex.devtools.debug.DebugServerProxy$1.getShakeHandsMessage(DebugServerProxy.java:84)
                                                                    at com.taobao.weex.devtools.debug.DebugServerProxy$1.onSuccess(DebugServerProxy.java:96)
                                                                    at com.taobao.weex.devtools.debug.DebugSocketClient.onOpen(DebugSocketClient.java:120)
```
十分明显，6.0手机权限问题，用的时候，尝试请求一下是否有权限。

**Comment by littleseven** [comment]
感谢反馈～ 
**Android6.0的权限控制收紧，android.permission.READ_PHONE_STATE 隐私相关，devtools后续版本会使用不需要申请这些权限的方法标记。**在DebugServerProxy中使用了getDeviceId方法来获取id标记一个debug中的设备，因而引用了  android.permission.READ_PHONE_STATE。
