### ISSUE TITLE
Android studio里运行，报错，界面空白

### ISSUE THREAD

**Issue by jiangfei891111** [alibaba/weex#951]
```
 launchInspector HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
                                                                               at com.taobao.weex.utils.WXHack.into(WXHack.java:232)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:345)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:320)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:332)
                                                                               at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:239)
                                                                               at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:229)
                                                                               at com.example.administrator.testweex2.WXApplication.onCreate(WXApplication.java:20)
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:149)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                                            Caused by: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.Class.forName(Class.java:308)
                                                                               at java.lang.Class.forName(Class.java:272)
                                                                               at com.taobao.weex.utils.WXHack.into(WXHack.java:230)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:345) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:320) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:332) 
                                                                               at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:239) 
                                                                               at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:229) 
                                                                               at com.example.administrator.testweex2.WXApplication.onCreate(WXApplication.java:20) 
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593) 
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:149) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5299) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.devtools.debug.DebugServerProxy" on path: DexPathList[[zip file "/data/app/com.example.administrator.testweex2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.administrator.testweex2-1/lib/arm, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at java.lang.Class.classForName(Native Method) 
                                                                               at java.lang.Class.forName(Class.java:308) 
                                                                               at java.lang.Class.forName(Class.java:272) 
                                                                               at com.taobao.weex.utils.WXHack.into(WXHack.java:230) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:345) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:320) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:332) 
                                                                               at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:239) 
                                                                               at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:229) 
                                                                               at com.example.administrator.testweex2.WXApplication.onCreate(WXApplication.java:20) 
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593) 
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:149) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5299) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
---
```

**Comment by sospartan** [comment]
这个异常是已经捕捉的 请贴一下完整的日志 或者日志文件上传一下

**Comment by jiangfei891111** [comment]
有人也出现了空白，说是安卓assets文件夹下有个main.js就会页面空白，改个名字就好了。请问为啥不能叫main.js

**Comment by sospartan** [comment]
`assets/main.js`是默认的js framework的位置

**Comment by sospartan** [comment]
@jiangfei891111 找到原因了?

**Comment by jiangfei891111** [comment]
之前是因为我的assets目录下，我放了个main.js.   改个名字就好了

**Comment by AllenVork** [comment]
我的安卓项目也报这个错误
